# : Manager [[[

[manager]
cwd = { fg = "#f0dedd" }

# Tab
tab_active = { fg = "#571d1f", bg = "#ffb3b1", bold = true }
tab_inactive = { fg = "#ffdad8", bg = "#3b080c" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffb546", bg = "#ffb546" }
marker_cut = { fg = "#ffdeac", bg = "#ffdeac" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e4c18d", bg = "#e4c18d" }

# Count
count_copied = { fg = "#281900", bg = "#ffdeac" }
count_cut = { fg = "#281900", bg = "#ffdeac" }
count_selected = { fg = "#571d1f", bg = "#e4c18d" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#ffb3b1" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#571d1f", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb3b1", fg = "#571d1f", bold = true }
normal_alt  = { bg = "#524342", fg = "#d7c1c0" }

# Select mode
select_main = { bg = "#e6bdbb", fg = "#442929", bold = true }
select_alt  = { bg = "#524342", fg = "#d7c1c0" }

# Unset mode
unset_main = { bg = "#e4c18d", fg = "#412d05", bold = true }
unset_alt  = { bg = "#524342", fg = "#d7c1c0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb3b1", bg = "#423736" }
progress_error = { fg = "#ffb4ab", bg = "#423736" }

# Permissions
permissions_t = { fg = "#bd504b" }
permissions_w = { fg = "#af7929" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ffa113" }
permissions_s = { fg = "#ff493f" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb3b1" }
active = { fg = "#e4c18d", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb3b1" }
value = { fg = "#f0dedd" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb3b1", bg = "#571d1f" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb3b1" }
title = {}
hovered = { fg = "#ffdeac", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423736" }
cand = { fg = "#ffb3b1" }
rest = { fg = "#571d1f" }
desc = { fg = "#f0dedd" }
separator = " ‚ñ∂ "
separator_style = { fg = "#f0dedd" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f0dedd" }
run = { fg = "#f0dedd" }
footer = { fg = "#442929", bg = "#e6bdbb" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e4c18d" }
title_warn = { fg = "#ffb3b1" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f0dedd" },
    { name = "*/", fg = "#ffb3b1" },
]

# : ]]]
