# : Manager [[[

[manager]
cwd = { fg = "#e7e0e8" }

# Tab
tab_active = { fg = "#3b255b", bg = "#d6bbfb", bold = true }
tab_inactive = { fg = "#eddcff", bg = "#250e44" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff7389", bg = "#ff7389" }
marker_cut = { fg = "#ffd9df", bg = "#ffd9df" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f1b7c2", bg = "#f1b7c2" }

# Count
count_copied = { fg = "#321019", bg = "#ffd9df" }
count_cut = { fg = "#321019", bg = "#ffd9df" }
count_selected = { fg = "#3b255b", bg = "#f1b7c2" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#d6bbfb" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#3b255b", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#d6bbfb", fg = "#3b255b", bold = true }
normal_alt  = { bg = "#4a454e", fg = "#cbc4cf" }

# Select mode
select_main = { bg = "#cec2da", fg = "#352d40", bold = true }
select_alt  = { bg = "#4a454e", fg = "#cbc4cf" }

# Unset mode
unset_main = { bg = "#f1b7c2", fg = "#4b252e", bold = true }
unset_alt  = { bg = "#4a454e", fg = "#cbc4cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#d6bbfb", bg = "#3b383e" }
progress_error = { fg = "#ffb4ab", bg = "#3b383e" }

# Permissions
permissions_t = { fg = "#8263a0" }
permissions_w = { fg = "#d83755" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff405e" }
permissions_s = { fg = "#9e43ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#d6bbfb" }
active = { fg = "#f1b7c2", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#d6bbfb" }
value = { fg = "#e7e0e8" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#d6bbfb", bg = "#3b255b" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#d6bbfb" }
title = {}
hovered = { fg = "#ffd9df", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3b383e" }
cand = { fg = "#d6bbfb" }
rest = { fg = "#3b255b" }
desc = { fg = "#e7e0e8" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e7e0e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e7e0e8" }
run = { fg = "#e7e0e8" }
footer = { fg = "#352d40", bg = "#cec2da" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f1b7c2" }
title_warn = { fg = "#d6bbfb" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e7e0e8" },
    { name = "*/", fg = "#d6bbfb" },
]

# : ]]]
