# : Manager [[[

[manager]
cwd = { fg = "#e8e0e8" }

# Tab
tab_active = { fg = "#402357", bg = "#ddb9f7", bold = true }
tab_inactive = { fg = "#f2daff", bg = "#2a0c41" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff7478", bg = "#ff7478" }
marker_cut = { fg = "#ffdadb", bg = "#ffdadb" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f4b7bb", bg = "#f4b7bb" }

# Count
count_copied = { fg = "#321015", bg = "#ffdadb" }
count_cut = { fg = "#321015", bg = "#ffdadb" }
count_selected = { fg = "#402357", bg = "#f4b7bb" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#ddb9f7" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#402357", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ddb9f7", fg = "#402357", bold = true }
normal_alt  = { bg = "#4b454d", fg = "#cdc3ce" }

# Select mode
select_main = { bg = "#d1c1d9", fg = "#372c3f", bold = true }
select_alt  = { bg = "#4b454d", fg = "#cdc3ce" }

# Unset mode
unset_main = { bg = "#f4b7bb", fg = "#4c2529", bold = true }
unset_alt  = { bg = "#4b454d", fg = "#cdc3ce" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ddb9f7", bg = "#3c383e" }
progress_error = { fg = "#ffb4ab", bg = "#3c383e" }

# Permissions
permissions_t = { fg = "#8b629f" }
permissions_w = { fg = "#e0323e" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff4146" }
permissions_s = { fg = "#bc41ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ddb9f7" }
active = { fg = "#f4b7bb", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ddb9f7" }
value = { fg = "#e8e0e8" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ddb9f7", bg = "#402357" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ddb9f7" }
title = {}
hovered = { fg = "#ffdadb", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3c383e" }
cand = { fg = "#ddb9f7" }
rest = { fg = "#402357" }
desc = { fg = "#e8e0e8" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e8e0e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e8e0e8" }
run = { fg = "#e8e0e8" }
footer = { fg = "#372c3f", bg = "#d1c1d9" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f4b7bb" }
title_warn = { fg = "#ddb9f7" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e8e0e8" },
    { name = "*/", fg = "#ddb9f7" },
]

# : ]]]
